{% set name = "vim" %}
{% set version = "8.2.3427" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vim/vim/archive/v{{ version }}.tar.gz
  sha256: 9150b55a4e5cc538ff04c71dc4f7219b838f6b9c884bebada426b5cca1e3b625

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - ncurses
  run:
    - python
    - ncurses

test:
  commands:
    - vim --version

about:
  home: https://www.vim.org/
  # vi(m) is licensed as charity-ware
  license: Vim
  license_file: runtime/doc/uganda.txt
  summary: Vim is a greatly improved version of the good old UNIX editor Vi
  dev_url: https://github.com/vim/vim

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scopatz
    - asford
    - matthiasdiener
